### ISSUE TITLE
SOAP client is slow

### ISSUE THREAD

**Issue by sanzcarlos** [CiscoDevNet/axl-python-zeep-samples#1]
Hello:

I am testing SOAP with python and I see that the creation of the SOAP client takes an average of 9 seconds, but with other programming languages like PHP this time is less than 1 second.

Is there any way to improve this time?

Regards,
Carlos Sanz

**Comment by npetreley** [comment]
PHP is definitely fast, but I don't experience that kind of delay with Python.  Is it possible that the delay is caused by the lack of a certificate?  The sample code doesn't specify a certificate because it's meant to be used by anyone.  But it might go faster if you specify the certificate where the code indicates you'd do so.  You'll still get a warning when you run the script, but not the same kind/number of warnings.

**Comment by dstaudt** [comment]
Have you enabled Zeep caching?  https://python-zeep.readthedocs.io/en/master/transport.html#transport-caching

This sample shows how to use it with the SqlLite plugin:

```python
from zeep.cache import SqliteCache
...
transport = Transport(session=session, timeout=10, cache=SqliteCache())
```

**Comment by dstaudt** [comment]
Will close shortly unless there is a continued issue

**Comment by sanzcarlos** [comment]
Hello:

Enabling the cache and updating the python version works faster for me. Thank you.
